const students = [
  {
    name: "Aarav Sharma",
    email: "aarav.sharma@example.com",
    phone: "9876543210",
    password: "securePass123",
    age: 20,
    grade: "A",
    profilePic: "https://example.com/profile1.jpg",
    enrollment: "ENR1001",
    type: "Full-Time",
    academicRecords: [],
    skills: [],
    extracurricularActivities: [],
    courses: [],
    attendance: []
  },
  {
    name: "Ishita Verma",
    email: "ishita.verma@example.com",
    phone: "9823456789",
    password: "strongPass456",
    age: 22,
    grade: "B",
    profilePic: "https://example.com/profile2.jpg",
    enrollment: "ENR1002",
    type: "Part-Time",
    academicRecords: [],
    skills: [],
    extracurricularActivities: [],
    courses: [],
    attendance: []
  },
  {
    name: "Rohan Gupta",
    email: "rohan.gupta@example.com",
    phone: "9812345678",
    password: "myPassword789",
    age: 21,
    grade: "A",
    profilePic: "https://example.com/profile3.jpg",
    enrollment: "ENR1003",
    type: "Full-Time",
    academicRecords: [],
    skills: [],
    extracurricularActivities: [],
    courses: [],
    attendance: []
  },
  {
    name: "Sneha Iyer",
    email: "sneha.iyer@example.com",
    phone: "9834567890",
    password: "pass123Strong",
    age: 23,
    grade: "B+",
    profilePic: "https://example.com/profile4.jpg",
    enrollment: "ENR1004",
    type: "Full-Time",
    academicRecords: [],
    skills: [],
    extracurricularActivities: [],
    courses: [],
    attendance: []
  },
  {
    name: "Vikram Nair",
    email: "vikram.nair@example.com",
    phone: "9845678901",
    password: "bestPassword999",
    age: 19,
    grade: "A+",
    profilePic: "https://example.com/profile5.jpg",
    enrollment: "ENR1005",
    type: "Part-Time",
    academicRecords: [],
    skills: [],
    extracurricularActivities: [],
    courses: [],
    attendance: []
  },
  {
    name: "Ananya Singh",
    email: "ananya.singh@example.com",
    phone: "9871234567",
    password: "newPass456",
    age: 22,
    grade: "A",
    profilePic: "https://example.com/profile6.jpg",
    enrollment: "ENR1006",
    type: "Full-Time",
    academicRecords: [],
    skills: [],
    extracurricularActivities: [],
    courses: [],
    attendance: []
  },
  {
    name: "Karan Joshi",
    email: "karan.joshi@example.com",
    phone: "9854321098",
    password: "karanPass789",
    age: 20,
    grade: "B+",
    profilePic: "https://example.com/profile7.jpg",
    enrollment: "ENR1007",
    type: "Part-Time",
    academicRecords: [],
    skills: [],
    extracurricularActivities: [],
    courses: [],
    attendance: []
  },
  {
    name: "Priya Deshmukh",
    email: "priya.deshmukh@example.com",
    phone: "9898765432",
    password: "priyaPass123",
    age: 21,
    grade: "A",
    profilePic: "https://example.com/profile8.jpg",
    enrollment: "ENR1008",
    type: "Full-Time",
    academicRecords: [],
    skills: [],
    extracurricularActivities: [],
    courses: [],
    attendance: []
  },
  {
    name: "Rahul Mehta",
    email: "rahul.mehta@example.com",
    phone: "9812345679",
    password: "rahulSecure987",
    age: 23,
    grade: "B",
    profilePic: "https://example.com/profile9.jpg",
    enrollment: "ENR1009",
    type: "Full-Time",
    academicRecords: [],
    skills: [],
    extracurricularActivities: [],
    courses: [],
    attendance: []
  },
  {
    name: "Tanvi Kulkarni",
    email: "tanvi.kulkarni@example.com",
    phone: "9876541230",
    password: "tanviPass888",
    age: 19,
    grade: "A+",
    profilePic: "https://example.com/profile10.jpg",
    enrollment: "ENR1010",
    type: "Part-Time",
    academicRecords: [],
    skills: [],
    extracurricularActivities: [],
    courses: [],
    attendance: []
  }
];

module.exports = students;
const extracurricularActivities = [
  {
    studentId: "STU1001", // Replace with actual ObjectId
    activityName: "Debate Club",
    type: "Public Speaking",
    position: "President",
    achievements: "Won 1st place in State-Level Debate Competition",
    details: "Organized multiple debates and mentored junior members.",
  },
  {
    studentId: "STU1001",
    activityName: "Basketball Team",
    type: "Sports",
    position: "Captain",
    achievements: "Led team to university championship",
    details: "Trained regularly and managed team strategy.",
  },
  {
    studentId: "STU1001",
    activityName: "Music Club",
    type: "Cultural",
    position: "Lead Guitarist",
    achievements: "Performed in annual fest and local events",
    details: "Played lead guitar in multiple college events.",
  },
  {
    studentId: "STU1001",
    activityName: "Coding Hackathons",
    type: "Tech",
    position: "Participant",
    achievements: "Secured top 3 positions in 2 national hackathons",
    details: "Built real-world projects using AI and automation.",
  },
  {
    studentId: "STU1001",
    activityName: "Photography Club",
    type: "Creative",
    position: "Member",
    achievements: "Featured in the college magazine",
    details: "Specialized in portrait and nature photography.",
  },

  {
    studentId: "STU1002",
    activityName: "Theater Group",
    type: "Drama",
    position: "Lead Actor",
    achievements: "Won best actor award in intercollege fest",
    details: "Played lead roles in multiple stage performances.",
  },
  {
    studentId: "STU1002",
    activityName: "Football Team",
    type: "Sports",
    position: "Midfielder",
    achievements: "Represented college at national level",
    details: "Played as a midfielder and assisted in multiple goals.",
  },
  {
    studentId: "STU1002",
    activityName: "Volunteer Work",
    type: "Social Service",
    position: "Team Leader",
    achievements: "Organized blood donation camps",
    details: "Led team to successfully conduct charity events.",
  },
  {
    studentId: "STU1002",
    activityName: "Chess Club",
    type: "Strategy",
    position: "Vice President",
    achievements: "Won 2nd place in university chess competition",
    details: "Regularly trained and played tournaments.",
  },
  {
    studentId: "STU1002",
    activityName: "Content Writing",
    type: "Creative",
    position: "Editor",
    achievements: "Published articles in college newspaper",
    details: "Wrote and edited content for the university magazine.",
  },
];

module.exports = extracurricularActivities;
const skills = [
  {
    studentId: "STU1001", // Replace with actual ObjectId
    skillName: "JavaScript",
    proficiency: "Advanced",
  },
  {
    studentId: "STU1001",
    skillName: "React.js",
    proficiency: "Intermediate",
  },
  {
    studentId: "STU1001",
    skillName: "Node.js",
    proficiency: "Advanced",
  },
  {
    studentId: "STU1001",
    skillName: "MongoDB",
    proficiency: "Intermediate",
  },
  {
    studentId: "STU1001",
    skillName: "CSS",
    proficiency: "Advanced",
  },

  {
    studentId: "STU1002",
    skillName: "Python",
    proficiency: "Advanced",
  },
  {
    studentId: "STU1002",
    skillName: "Django",
    proficiency: "Intermediate",
  },
  {
    studentId: "STU1002",
    skillName: "Machine Learning",
    proficiency: "Beginner",
  },
  {
    studentId: "STU1002",
    skillName: "SQL",
    proficiency: "Advanced",
  },
  {
    studentId: "STU1002",
    skillName: "Data Structures",
    proficiency: "Advanced",
  },
];

module.exports = skills;
const extracurricularActivities = [
  {
    studentId: "STU1001", // Replace with actual ObjectId
    activityName: "Debate Club",
    type: "Public Speaking",
    position: "President",
    achievements: "Won 1st place in State-Level Debate Competition",
    details: "Organized multiple debates and mentored junior members.",
  },
  {
    studentId: "STU1001",
    activityName: "Basketball Team",
    type: "Sports",
    position: "Captain",
    achievements: "Led team to university championship",
    details: "Trained regularly and managed team strategy.",
  },
  {
    studentId: "STU1001",
    activityName: "Music Club",
    type: "Cultural",
    position: "Lead Guitarist",
    achievements: "Performed in annual fest and local events",
    details: "Played lead guitar in multiple college events.",
  },
  {
    studentId: "STU1001",
    activityName: "Coding Hackathons",
    type: "Tech",
    position: "Participant",
    achievements: "Secured top 3 positions in 2 national hackathons",
    details: "Built real-world projects using AI and automation.",
  },
  {
    studentId: "STU1001",
    activityName: "Photography Club",
    type: "Creative",
    position: "Member",
    achievements: "Featured in the college magazine",
    details: "Specialized in portrait and nature photography.",
  },

  {
    studentId: "STU1002",
    activityName: "Theater Group",
    type: "Drama",
    position: "Lead Actor",
    achievements: "Won best actor award in intercollege fest",
    details: "Played lead roles in multiple stage performances.",
  },
  {
    studentId: "STU1002",
    activityName: "Football Team",
    type: "Sports",
    position: "Midfielder",
    achievements: "Represented college at national level",
    details: "Played as a midfielder and assisted in multiple goals.",
  },
  {
    studentId: "STU1002",
    activityName: "Volunteer Work",
    type: "Social Service",
    position: "Team Leader",
    achievements: "Organized blood donation camps",
    details: "Led team to successfully conduct charity events.",
  },
  {
    studentId: "STU1002",
    activityName: "Chess Club",
    type: "Strategy",
    position: "Vice President",
    achievements: "Won 2nd place in university chess competition",
    details: "Regularly trained and played tournaments.",
  },
  {
    studentId: "STU1002",
    activityName: "Content Writing",
    type: "Creative",
    position: "Editor",
    achievements: "Published articles in college newspaper",
    details: "Wrote and edited content for the university magazine.",
  },
];

module.exports = extracurricularActivities;
const extracurricularActivities = [
  {
    studentId: "STU1001", // Replace with actual ObjectId
    activityName: "Debate Club",
    type: "Public Speaking",
    position: "President",
    achievements: "Won 1st place in State-Level Debate Competition",
    details: "Organized multiple debates and mentored junior members.",
  },
  {
    studentId: "STU1001",
    activityName: "Basketball Team",
    type: "Sports",
    position: "Captain",
    achievements: "Led team to university championship",
    details: "Trained regularly and managed team strategy.",
  },
  {
    studentId: "STU1001",
    activityName: "Music Club",
    type: "Cultural",
    position: "Lead Guitarist",
    achievements: "Performed in annual fest and local events",
    details: "Played lead guitar in multiple college events.",
  },
  {
    studentId: "STU1001",
    activityName: "Coding Hackathons",
    type: "Tech",
    position: "Participant",
    achievements: "Secured top 3 positions in 2 national hackathons",
    details: "Built real-world projects using AI and automation.",
  },
  {
    studentId: "STU1001",
    activityName: "Photography Club",
    type: "Creative",
    position: "Member",
    achievements: "Featured in the college magazine",
    details: "Specialized in portrait and nature photography.",
  },

  {
    studentId: "STU1002",
    activityName: "Theater Group",
    type: "Drama",
    position: "Lead Actor",
    achievements: "Won best actor award in intercollege fest",
    details: "Played lead roles in multiple stage performances.",
  },
  {
    studentId: "STU1002",
    activityName: "Football Team",
    type: "Sports",
    position: "Midfielder",
    achievements: "Represented college at national level",
    details: "Played as a midfielder and assisted in multiple goals.",
  },
  {
    studentId: "STU1002",
    activityName: "Volunteer Work",
    type: "Social Service",
    position: "Team Leader",
    achievements: "Organized blood donation camps",
    details: "Led team to successfully conduct charity events.",
  },
  {
    studentId: "STU1002",
    activityName: "Chess Club",
    type: "Strategy",
    position: "Vice President",
    achievements: "Won 2nd place in university chess competition",
    details: "Regularly trained and played tournaments.",
  },
  {
    studentId: "STU1002",
    activityName: "Content Writing",
    type: "Creative",
    position: "Editor",
    achievements: "Published articles in college newspaper",
    details: "Wrote and edited content for the university magazine.",
  },
];

module.exports = extracurricularActivities;

 [
    { 
      id: 1, 
      date: 'March 7, 2025', 
      course: 'CS 401 - Advanced Programming', 
      status: 'Present', 
      percentage: 100,
      timeIn: '09:30 AM',
      timeOut: '11:20 AM',
      duration: '1h 50m'
    },
    { 
      id: 2, 
      date: 'March 6, 2025', 
      course: 'MATH 301 - Applied Calculus', 
      status: 'Late', 
      percentage: 60,
      timeIn: '01:15 PM',
      timeOut: '03:00 PM',
      duration: '1h 45m'
    },
    { 
      id: 3, 
      date: 'March 6, 2025', 
      course: 'CS 401 - Advanced Programming', 
      status: 'Present', 
      percentage: 100,
      timeIn: '09:30 AM',
      timeOut: '11:20 AM',
      duration: '1h 50m'
    },
    { 
      id: 4, 
      date: 'March 5, 2025', 
      course: 'PHYS 201 - Physics II', 
      status: 'Absent', 
      percentage: 0,
      timeIn: '--:--',
      timeOut: '--:--',
      duration: '--'
    },
    { 
      id: 5, 
      date: 'March 5, 2025', 
      course: 'MATH 301 - Applied Calculus', 
      status: 'Present', 
      percentage: 100,
      timeIn: '01:00 PM',
      timeOut: '03:00 PM',
      duration: '2h 00m'
    },
    { 
      id: 6, 
      date: 'March 4, 2025', 
      course: 'CS 401 - Advanced Programming', 
      status: 'Present', 
      percentage: 100,
      timeIn: '09:30 AM',
      timeOut: '11:20 AM',
      duration: '1h 50m'
    },
    { 
      id: 7, 
      date: 'March 3, 2025', 
      course: 'CS 401 - Advanced Programming', 
      status: 'Excused', 
      percentage: 100,
      timeIn: '--:--',
      timeOut: '--:--',
      duration: '--',
      note: 'Medical appointment'
    },
  ]

  
